import type { Metadata } from "next";
import { Urbanist, Inter, Manrope } from "next/font/google";
import "./globals.css";
import Navbar from "@/src/components/common/Navbar/Navbar";
import Footer from "@/src/components/common/Footer/Footer";

const urbanist = Urbanist({ subsets: ["latin"], variable: "--font-urbanist" });
const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });
const manrope = Manrope({ subsets: ["latin"], variable: "--font-manrope" });

import { ThemeProvider } from "@/src/components/theme-provider";
import { ThemeConfigProvider } from "@/src/context/ThemeConfigContext";

export const metadata: Metadata = {
  title: "AP2L",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning className={`${urbanist.variable} ${inter.variable} ${manrope.variable}`}>
      <body suppressHydrationWarning className="font-sans">
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem={false}
          disableTransitionOnChange
        >
          <ThemeConfigProvider>
            <Navbar />
            <main>{children}</main>
            <Footer />
          </ThemeConfigProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
